<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Part II: The Gaussian intercepts-only model | Workshop on Bayesian Data Analysis &amp; Priors</title>
  <meta name="description" content="This site is a hub for the materials for our workshop on Bayesian data analysis and priors." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Part II: The Gaussian intercepts-only model | Workshop on Bayesian Data Analysis &amp; Priors" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This site is a hub for the materials for our workshop on Bayesian data analysis and priors." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Part II: The Gaussian intercepts-only model | Workshop on Bayesian Data Analysis &amp; Priors" />
  
  <meta name="twitter:description" content="This site is a hub for the materials for our workshop on Bayesian data analysis and priors." />
  

<meta name="author" content="Riccardo Fusaroli &amp; Chris Cox" />


<meta name="date" content="2022-01-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="part-iii-linear-regression-with-a-dichotomous-predictor.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Part I: Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#structure-of-this-workshop"><i class="fa fa-check"></i><b>1.1</b> Structure of this Workshop</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#link-to-introductory-video"><i class="fa fa-check"></i><b>1.2</b> Link to Introductory Video</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="part-ii-the-gaussian-intercepts-only-model.html"><a href="part-ii-the-gaussian-intercepts-only-model.html"><i class="fa fa-check"></i><b>2</b> Part II: The Gaussian intercepts-only model</a></li>
<li class="chapter" data-level="3" data-path="part-iii-linear-regression-with-a-dichotomous-predictor.html"><a href="part-iii-linear-regression-with-a-dichotomous-predictor.html"><i class="fa fa-check"></i><b>3</b> Part III: Linear regression with a dichotomous predictor</a></li>
<li class="chapter" data-level="4" data-path="part-iv-multi-level-model-with-repeated-measures.html"><a href="part-iv-multi-level-model-with-repeated-measures.html"><i class="fa fa-check"></i><b>4</b> Part IV: Multi-level model with repeated measures</a></li>
<li class="chapter" data-level="5" data-path="part-v-multi-level-model-based-on-informed-priors.html"><a href="part-v-multi-level-model-based-on-informed-priors.html"><i class="fa fa-check"></i><b>5</b> Part V: Multi-level model based on informed priors</a>
<ul>
<li class="chapter" data-level="5.1" data-path="part-v-multi-level-model-based-on-informed-priors.html"><a href="part-v-multi-level-model-based-on-informed-priors.html#section"><i class="fa fa-check"></i><b>5.1</b> </a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="recommendations-for-further-study.html"><a href="recommendations-for-further-study.html"><i class="fa fa-check"></i><b>6</b> Recommendations for Further Study</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Workshop on Bayesian Data Analysis &amp; Priors</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="part-ii-the-gaussian-intercepts-only-model" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Part II: The Gaussian intercepts-only model</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#if you don&#39;t have the pacman package loaded on your computer, uncomment the next line, install pacman, and load in the required packages</span></span>
<span id="cb1-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&#39;pacman&#39;)</span></span>
<span id="cb1-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#load the required packages:</span></span>
<span id="cb1-4"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-4" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, </span>
<span id="cb1-5"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-5" aria-hidden="true" tabindex="-1"></a>       glue,</span>
<span id="cb1-6"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-6" aria-hidden="true" tabindex="-1"></a>       data.table,</span>
<span id="cb1-7"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-7" aria-hidden="true" tabindex="-1"></a>       dplyr,</span>
<span id="cb1-8"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-8" aria-hidden="true" tabindex="-1"></a>       moments,</span>
<span id="cb1-9"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-9" aria-hidden="true" tabindex="-1"></a>       tidybayes,</span>
<span id="cb1-10"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-10" aria-hidden="true" tabindex="-1"></a>       ggplot2,</span>
<span id="cb1-11"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-11" aria-hidden="true" tabindex="-1"></a>       ggridges,</span>
<span id="cb1-12"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-12" aria-hidden="true" tabindex="-1"></a>       plyr,</span>
<span id="cb1-13"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-13" aria-hidden="true" tabindex="-1"></a>       ellipse,</span>
<span id="cb1-14"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-14" aria-hidden="true" tabindex="-1"></a>       brms,</span>
<span id="cb1-15"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-15" aria-hidden="true" tabindex="-1"></a>       cowplot,</span>
<span id="cb1-16"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb1-16" aria-hidden="true" tabindex="-1"></a>       viridis)</span></code></pre></div>
<p>PART I:</p>
<p>Introduction to the data:</p>
<p>Our research question concerns the hyperarticulation hypothesis of infant-directed speech. Do caregivers produce more peripheral vowels in infant-directed speech (IDS) compared to adult-directed speech (ADS)? To answer this question, we manually analysed 9267 extracted vowel tokens from individual caregivers’ IDS and ADS. In order eliminate inter-individual differences in formant values that occur due to physiological characteristics, we first z-score-normalised the formant data according to participant and then computed the total area of each caregiver’s ADS and IDS vowel space. We used this measure to calculate a standardised mean difference score: Cohen’s d.
The dataset we will analyse here consists of the following information:
i) Subject (i.e. unique participant pseudonym),
ii) Register (i.e. the speech style used - adult-directed speech (ADS) vs. infant-directed speech (IDS)),
iii) ArticulationS (i.e. the dependent variable - represents a standardised version of the vowel space),
iv) ChildSex (i.e. male vs. female),
v) ChildAge (i.e. from 11 m to 24 m),
vi) First_child (whether this is the caregiver’s first child).</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load the data:</span></span>
<span id="cb2-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb2-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;vowel_space_area_data.csv&#39;</span>)</span>
<span id="cb2-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(d)</span></code></pre></div>
<pre><code>## Rows: 48
## Columns: 7
## $ X             &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
## $ Subject       &lt;chr&gt; &quot;AF&quot;, &quot;AN&quot;, &quot;CL&quot;, &quot;DM&quot;, &quot;IA&quot;, &quot;JA&quot;, &quot;JE&quot;, &quot;KA&quot;, &quot;KV&quot;, &quot;L…
## $ Register      &lt;chr&gt; &quot;ADS&quot;, &quot;ADS&quot;, &quot;ADS&quot;, &quot;ADS&quot;, &quot;ADS&quot;, &quot;ADS&quot;, &quot;ADS&quot;, &quot;ADS&quot;, …
## $ ArticulationS &lt;dbl&gt; 0.76015464, -1.28956792, -0.85914839, -0.81478879, 0.797…
## $ ChildSex      &lt;chr&gt; &quot;m&quot;, &quot;m&quot;, &quot;f&quot;, &quot;m&quot;, &quot;f&quot;, &quot;m&quot;, &quot;f&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;…
## $ ChildAge      &lt;int&gt; 20, 22, 16, 12, 23, 24, 21, 14, 16, 16, 12, 16, 23, 12, …
## $ First_child   &lt;chr&gt; &quot;No&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;Yes&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;Yes&quot;…</code></pre>
<p>Let’s start by building an intercepts-only model with ArticulationS as our dependent variable. We’ll use the function bf() to specify the structure of this first model as follows:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb4-1" aria-hidden="true" tabindex="-1"></a>Articulation_f1 <span class="ot">&lt;-</span> <span class="fu">bf</span>(ArticulationS <span class="sc">~</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Now that we have our model formula in place, we can use the function get_prior() to tell us which priors need to be specified for this model structure. This function also provides suggestions for default priors:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_prior</span>(Articulation_f1, </span>
<span id="cb5-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb5-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> d, </span>
<span id="cb5-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb5-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> gaussian)</span></code></pre></div>
<pre><code>##                    prior     class coef group resp dpar nlpar bound  source
##  student_t(3, -0.4, 2.5) Intercept                                  default
##     student_t(3, 0, 2.5)     sigma                                  default</code></pre>
<p>The output of the above function tells us that we need to specify a prior for the intercept (i.e. ‘Intercept’) and the residual variation (i.e. ‘sigma’). This output also provides suggestions for priors (e.g., student_t(3, -0.2, 2.5) for the Intercept), but let’s ignore those for now.</p>
<p>Let’s start by specifying weakly informative Gaussian priors for the intercept and sigma, centered at 0 with a standard deviation of 10. These priors allow for a large range of values for the intercept and residual variation (e.g. with this prior, we are specifying that we expect 95 % of the distribution to be between -20 and 20). The tails of these distributions thus represent very large (and unrealistic) values for our parameters of interest - but let’s see where these weakly informative priors take us.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb7-1" aria-hidden="true" tabindex="-1"></a>weakly_informative_priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb7-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">class =</span> sigma))</span></code></pre></div>
<p>Before building an actual model of the hyperarticulation data, we can first run a model to determine whether our prior expectations generate appropriate values. This is known as a prior predictive check. The following code samples from the prior distributions we have specified above, without taking the actual data into account:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I&#39;ve provided comments on the parameters that were not introduced to you in the lecture, </span></span>
<span id="cb8-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#so you have an idea of what they do:</span></span>
<span id="cb8-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-3" aria-hidden="true" tabindex="-1"></a>Articulation_m1_prior0 <span class="ot">&lt;-</span> </span>
<span id="cb8-4"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span>(</span>
<span id="cb8-5"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-5" aria-hidden="true" tabindex="-1"></a>    Articulation_f1, </span>
<span id="cb8-6"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> d,</span>
<span id="cb8-7"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> gaussian,</span>
<span id="cb8-8"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior =</span> weakly_informative_priors,</span>
<span id="cb8-9"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_prior =</span> <span class="st">&quot;only&quot;</span>, <span class="co">#this term specifies that the model only samples from the </span></span>
<span id="cb8-10"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-10" aria-hidden="true" tabindex="-1"></a>                           <span class="co">#priors specified. </span></span>
<span id="cb8-11"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-12"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="co">#file = &quot;Articulation_m0_prior0&quot;, #this parameter saves the model in your working </span></span>
<span id="cb8-13"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-13" aria-hidden="true" tabindex="-1"></a>                                      <span class="co">#directory to allow you to load the model at a later point.</span></span>
<span id="cb8-14"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">iter =</span> <span class="dv">2000</span>, <span class="co">#this iter parameter specifies the total number of iterations of the </span></span>
<span id="cb8-15"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-15" aria-hidden="true" tabindex="-1"></a>                 <span class="co">#Markov Chain Monte Carlo (MCMC) algorithm. We run prior predictive checks </span></span>
<span id="cb8-16"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-16" aria-hidden="true" tabindex="-1"></a>                 <span class="co">#with a small number of iterations as we are not interested in the statistical </span></span>
<span id="cb8-17"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-17" aria-hidden="true" tabindex="-1"></a>                 <span class="co">#results - we simply use these models to plot samples from our specified priors. </span></span>
<span id="cb8-18"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">warmup =</span> <span class="dv">200</span>, <span class="co">#this parameter specifies number of warmup (aka burn-in) iterations.</span></span>
<span id="cb8-19"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">cores =</span> <span class="dv">2</span>, <span class="co"># Number of CPU cores to use when executing the chains - 2 should be more than </span></span>
<span id="cb8-20"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-20" aria-hidden="true" tabindex="-1"></a>               <span class="co"># enough, but you can increase this if the models are taking too long to run.</span></span>
<span id="cb8-21"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">chains =</span> <span class="dv">2</span>, <span class="co"># Number of Markov chains (defaults to 4).</span></span>
<span id="cb8-22"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">backend =</span> <span class="st">&quot;cmdstanr&quot;</span>, <span class="co">#feel free to uncomment this and the following line if you have </span></span>
<span id="cb8-23"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-23" aria-hidden="true" tabindex="-1"></a>                           <span class="co">#installed the “cmdstanr” package - runtime will be a little faster.</span></span>
<span id="cb8-24"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">threads =</span> <span class="fu">threading</span>(<span class="dv">2</span>), </span>
<span id="cb8-25"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>, <span class="at">max_treedepth =</span> <span class="dv">20</span>)) <span class="co">#these parameters control the MCMC </span></span>
<span id="cb8-26"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-26" aria-hidden="true" tabindex="-1"></a>                                                            <span class="co">#sampler’s behaviour in various ways </span></span>
<span id="cb8-27"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb8-27" aria-hidden="true" tabindex="-1"></a>                                                            <span class="co">#(e.g., step size). You can leave them like this for now.</span></span></code></pre></div>
<p>Let’s plot some predictions from our priors by using the following pp_check() function. This plot shows the predictions from our prior distributions in blue and the actual data in black. This allows us to check whether our specifications of prior distributions are appropriate.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(Articulation_m1_prior0, <span class="at">ndraws =</span> <span class="dv">100</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Run the same pp_check() function above a couple of times and observe the results. You’ll notice that the prior predictive plots vary each time you run the code; that’s because the pp_check() function takes random samples from the model we specified above. It’s therefore good practice to run the pp_check() function a couple of times to make sure that the plots show a pattern in the prior predictions of the model.</p>
<p>Let’s compare the predictions from our priors (in blue) with those of the data (in black); the predictions appear to have a much larger (and unrealistic) range than that shown by the data. Before moving on, try to answer the following question:</p>
<p>Q1: How should we modify our priors to obtain more realistic predictions from our prior distributions?</p>
<p>Write your answer here:</p>
<hr />
<p>As mentioned above, by specifying the standard deviations of the above priors as 10, we are saying that we expect approximately 95% of the distribution of standardized measures (i.e. ArticulationS) to be between -20 and 20 sds from the mean; however, given our prior knowledge about the measure, a distance of 20 sds from the mean would be extremely unrealistic. Let’s try to capture our prior knowledge of the measure in our specification of the priors.</p>
<p>What would be a reasonable ArticulationS value to expect given our prior knowledge about effect sizes? Effect sizes are usually distributed around ± 2 - to capture this, we can specify a standard deviation of 1 (i.e. with this, we expect approximately 95 % of the distribution to fall within ± 2 x SD ). For the standard deviation of the residual variation, sigma, we expect this to be on the same scale, and as discussed in the slides, we can specify a mean of 1 and standard deviation of 0.5:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb10-1" aria-hidden="true" tabindex="-1"></a>more_informative_priors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb10-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> Intercept),</span>
<span id="cb10-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">1</span>, <span class="fl">0.5</span>), <span class="at">class =</span> sigma))</span></code></pre></div>
<p>Similar to before, then, let’s run a prior predictive check to determine whether these priors provide more appropriate values:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-1" aria-hidden="true" tabindex="-1"></a>Articulation_m1_prior <span class="ot">&lt;-</span> </span>
<span id="cb11-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span>(</span>
<span id="cb11-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-3" aria-hidden="true" tabindex="-1"></a>    Articulation_f1, </span>
<span id="cb11-4"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> d,</span>
<span id="cb11-5"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> gaussian,</span>
<span id="cb11-6"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior =</span> more_informative_priors,</span>
<span id="cb11-7"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_prior =</span> <span class="st">&quot;only&quot;</span>, </span>
<span id="cb11-8"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">iter =</span> <span class="dv">2000</span>,</span>
<span id="cb11-9"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">warmup =</span> <span class="dv">200</span>,</span>
<span id="cb11-10"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">backend =</span> <span class="st">&quot;cmdstanr&quot;</span>, </span>
<span id="cb11-11"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">threads =</span> <span class="fu">threading</span>(<span class="dv">2</span>),</span>
<span id="cb11-12"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">cores =</span> <span class="dv">2</span>,</span>
<span id="cb11-13"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">chains =</span> <span class="dv">2</span>,</span>
<span id="cb11-14"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">#file = &quot;Articulation_m1_prior&quot;,</span></span>
<span id="cb11-15"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb11-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>, <span class="at">max_treedepth =</span> <span class="dv">20</span>))</span></code></pre></div>
<p>Q2: Before you take a look at the prior predictive check plots, how do you expect this model to differ from that of the first and why?</p>
<p>Answer:</p>
<hr />
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prior predictive check for the weakly informative priors:</span></span>
<span id="cb12-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(Articulation_m1_prior0, <span class="at">ndraws =</span> <span class="dv">100</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prior predictive check for the more informative priors:</span></span>
<span id="cb13-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(Articulation_m1_prior, <span class="at">ndraws =</span> <span class="dv">100</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<p>Now that our priors appear to be within the order of magnitude of ArticulationS that we expect (i.e. not 10 times more than the range we expect), let’s use these priors to build an intercepts-only model for the actual data:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-1" aria-hidden="true" tabindex="-1"></a>Articulation_m1 <span class="ot">&lt;-</span> </span>
<span id="cb14-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span>(</span>
<span id="cb14-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-3" aria-hidden="true" tabindex="-1"></a>    Articulation_f1,</span>
<span id="cb14-4"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> d,</span>
<span id="cb14-5"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_pars =</span> <span class="fu">save_pars</span>(<span class="at">all =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-6"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> gaussian,</span>
<span id="cb14-7"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior =</span> more_informative_priors,</span>
<span id="cb14-8"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">#file = &quot;Articulation_m1&quot;,</span></span>
<span id="cb14-9"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_prior =</span> T,</span>
<span id="cb14-10"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">iter =</span> <span class="dv">5000</span>,</span>
<span id="cb14-11"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">warmup =</span> <span class="dv">1000</span>,</span>
<span id="cb14-12"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">cores =</span> <span class="dv">2</span>,</span>
<span id="cb14-13"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">chains =</span> <span class="dv">2</span>,</span>
<span id="cb14-14"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">backend =</span> <span class="st">&quot;cmdstanr&quot;</span>,</span>
<span id="cb14-15"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">threads =</span> <span class="fu">threading</span>(<span class="dv">2</span>),</span>
<span id="cb14-16"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">list</span>(</span>
<span id="cb14-17"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">adapt_delta =</span> <span class="fl">0.99</span>,</span>
<span id="cb14-18"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb14-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">max_treedepth =</span> <span class="dv">15</span> ))</span></code></pre></div>
<p>Now that we have our first model, we can conduct posterior predictive checks to make sure that our model has captured the data.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pp_check</span>(Articulation_m1, <span class="at">ndraws =</span> <span class="dv">100</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The plot indicates that our model captures the overall distribution of our dependent variable (although there is a lot of uncertainty in model predictions).</p>
<p>Another way to ensure that our model represents a good fit to the data is to plot prior-posterior update plots. These plots show how our model updates from our priors after seeing the data. To plot these data, we’ll use as_draws_df() to sample from the prior and posterior distributions for the relevant parameters (i.e. ‘Intercept’ and ‘sigma’ in this case) from the above model.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#overview of model parameters:</span></span>
<span id="cb16-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">variables</span>(Articulation_m1)</span></code></pre></div>
<pre><code>## [1] &quot;b_Intercept&quot;     &quot;sigma&quot;           &quot;Intercept&quot;       &quot;prior_Intercept&quot;
## [5] &quot;prior_sigma&quot;     &quot;lp__&quot;</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Sample the parameters of interest:</span></span>
<span id="cb18-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb18-2" aria-hidden="true" tabindex="-1"></a>Posterior_m1 <span class="ot">&lt;-</span> <span class="fu">as_draws_df</span>(Articulation_m1)</span>
<span id="cb18-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot the prior-posterior update plot for the intercept:</span></span>
<span id="cb18-4"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Posterior_m1) <span class="sc">+</span></span>
<span id="cb18-5"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(prior_Intercept), <span class="at">fill=</span><span class="st">&quot;steelblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>,<span class="at">alpha=</span><span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(b_Intercept), <span class="at">fill=</span><span class="st">&quot;#FC4E07&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>,<span class="at">alpha=</span><span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb18-7"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot the prior-posterior update plot for sigma:</span></span>
<span id="cb19-2"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Posterior_m1) <span class="sc">+</span></span>
<span id="cb19-3"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(prior_sigma), <span class="at">fill=</span><span class="st">&quot;steelblue&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>,<span class="at">alpha=</span><span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(sigma), <span class="at">fill=</span><span class="st">&quot;#FC4E07&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>,<span class="at">alpha=</span><span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb19-5"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p>These prior-posterior update plots (with the prior in blue and the posterior in orange) indicate that our model has learned after seeing the data - great stuff! To check your intuitions, try to answer the following question:</p>
<p>Q3: How do you think these prior-posterior update plots would compare with those of the weakly informative priors we specified above (repeated below)?</p>
<p>weakly_informative_priors &lt;- c(
prior(normal(0, 10), class = Intercept),
prior(normal(0, 10), class = sigma))</p>
<p>Answer:</p>
<hr />
<p>BONUS POINTS: Try to adapt the code for Articulation_m0 and run a model with the weakly-informative priors:</p>
<p>Now that we have checked (via posterior predictive checks and prior-posterior update plots) that our model captures relevant information, let’s have a look at the model output:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="part-ii-the-gaussian-intercepts-only-model.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Articulation_m1)</span></code></pre></div>
<pre><code>##  Family: gaussian 
##   Links: mu = identity; sigma = identity 
## Formula: ArticulationS ~ 1 
##    Data: d (Number of observations: 48) 
##   Draws: 2 chains, each with iter = 4000; warmup = 0; thin = 1;
##          total post-warmup draws = 8000
## 
## Population-Level Effects: 
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept    -0.34      0.14    -0.62    -0.07 1.00     4821     4530
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma     1.02      0.11     0.84     1.25 1.00     3997     3903
## 
## Draws were sampled using sample(hmc). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>The model output gives a summary of the model parameters and then provides estimates of ‘Population-level Effects’ and ‘Family Specific Parameters.’ Let’s go through the ‘Population-level Effects’ and ‘Family Specific Parameters’ from top to bottom and left to right:</p>
<ul>
<li>The Estimate(s) obtained for the Intercept is centered on approx. -0.34 and has an estimated error of 0.15. The 95 % credible interval is<br />
approximately [-.63; -.04]).</li>
<li>In the ‘Family-Specific Parameters’ section, the residual variation (i.e., sigma) is estimated to be approximately 1.02 [0.85; 1.25].</li>
<li>The Rhat values provide information about the convergence of the algorithm. Rhat values close to 1 suggest that the model has converged.</li>
<li>The Bulk_ESS and Tail_ESS (effective sample size (ESS)) capture the sampling efficiency in the bulk and tails of the distribution.</li>
</ul>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="part-iii-linear-regression-with-a-dichotomous-predictor.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
